### ISSUE TITLE
portpicker is not on conda-forge

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/altair_data_server-feedstock#1]
This package depends on portpicker, which is not on conda-forge. Is it an optional dependency, or does someone need to make a feedstock?

I can probably make the feedstock if required, assuming it's noarch and there's nothing complicated. But if it's really optional, then removing the dependency could be a better option.

**Comment by ocefpaf** [comment]
Looks like it is a hard requirement, see https://github.com/altair-viz/altair_data_server/blob/master/requirements.txt#L2

A PR to add it would be nice. Try to create the PR with `grayskull pypi portpicker`  it will save you some time setting the recipe up.

**Comment by jamesmyatt** [comment]
Thanks @ocefpaf . I thought as much.
